spring:
  profiles:
    active: dev

mybatis:
  type-aliases-package: com.yiseven.zhoudaxiao.entity
  mapper-locations: classpath:mapper/*/*.xml

pagehelper:
  helper-dialect: mysql
  params: count=countSql
  reasonable: false
