server:
  port: 8889

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/zhoudaxiao?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&failOverReadOnly=false
    username: root
    password: admin
  redis:
    host: 127.0.0.1
    port: 6379
    timeout: 3000
logging:
  config: classpath:log4j-dev.xml

qcloud:
  secretId: AKIDY2Ocu6RkBIEtIXvCcmhOoxwf8KFyZgdS
  secretKey: h9KEuMXTFl23qOhjU6anjP4WidPvBC0a
  region: ap-guangzhou
  bucketName: yiseven-1300292849
  url: https://yiseven-1300292849.cos.ap-guangzhou.myqcloud.com/